name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '12 11 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: gradle/wrapper-validation-action@v1
    - name: gradle cache 
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: NVD cache 
      uses: actions/cache@v1
      with:
        path: ~/.gradle/dependency-check-data
        key: ${{ runner.os }}-nvd-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-nvd-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew jar check packageLicenseReport packageJavadoc packageSources dependencyUpdates packageCoverageReport --info --stacktrace
    - name: Upload msgdata package
      uses: actions/upload-artifact@v2
      with:
        name: messy-${{github.run_number}}-msgdata
        path: msgdata/build/libs 
    - name: Upload msgio package
      uses: actions/upload-artifact@v2
      with:
        name: messy-${{github.run_number}}-msgio
        path: msgio/build/libs 
    - name: Send coverage information to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
